# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bryce Fischer
tagline:          Home of the unoriginal title
url:              http://vbfischer.github.com
paginate:         1
baseurl:          /
author:
  name:           Vincent Bryce Fischer
  url:            https://twitter.com/vbfischer
  email:          bryce@berzerker-soft.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vbfischer/vbfischer.github.com

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
